export type PortfolioChunk = { id: string; section: 'profile' | 'projects' | 'experience' | 'credentials' | 'contact'; title: string; content: string; keywords: string[] }

export const portfolioChunks: PortfolioChunk[] = [
  { id: 'profile', section: 'profile', title: 'Profile', content: 'Joseph Macibi is a Senior Backend and AI Engineer based in Nairobi, Kenya. He designs production-grade Java and Spring Boot microservices and works with RAG architectures, NLP, and neural networks for fintech platforms. The portfolio says he has 4+ years building and an AI fintech focus.', keywords: ['joseph','joe','macibi','senior','backend','ai','engineer','nairobi','java','spring','boot','rag','nlp','neural','fintech','years'] },
  { id: 'project-mini-wakili', section: 'projects', title: 'Mini Wakili', content: 'Mini Wakili (repository: mini_wakili.py) is a modular Python scaffold for a grounded legal research agent. It separates orchestration, retrieval, legal-AI safety, document chunking, citations, and human-in-the-loop controls. Its local Kenyan citation corpus contains 20+ curated law, regulatory, and clearly labeled synthetic internal-policy materials. It is decision-support infrastructure, not legal advice, and materials should be verified against current official sources.', keywords: ['mini','wakili','mini_wakili.py','python','rag','grounded','legal','research','agent','orchestration','retrieval','chunking','citations','safety','human','loop','kenya','corpus','legal advice'] },
  { id: 'project-kiotapay', section: 'projects', title: 'KiotaPay streaming app', content: 'KiotaPay streaming app (repository: kiotapay-streaming-pdf-s3-upload) is one Spring Boot application using Java 25. It streams invoice PDFs generated with OpenPDF through a PipedOutputStream into multipart S3 uploads, using RabbitMQ for asynchronous jobs, MinIO for local object storage, bounded concurrency, retries, backpressure, and authenticated upload endpoints. The design keeps only the current upload part in memory rather than materializing the complete file.', keywords: ['kiotapay','streaming','pdf','s3','upload','java','25','spring','boot','openpdf','pipedoutputstream','multipart','rabbitmq','minio','invoice','bounded','concurrency','retry','backpressure','async','asynchronous'] },
  { id: 'project-infrarecord', section: 'projects', title: 'InfraRecord', content: 'InfraRecord is an infrastructure observability and governance platform for hybrid cloud environments. It uses TypeScript, Kafka, and AI optimization to create audit trails, ingest live metrics, and surface AI-driven resource optimization.', keywords: ['infrarecord','infrastructure','observability','governance','hybrid','cloud','typescript','kafka','audit','metrics','optimization'] },
  { id: 'project-chess3d', section: 'projects', title: 'Chess3D', content: 'Chess3D is an interactive browser chess game with custom Blender models and a Web Worker game AI. It uses TypeScript, Three.js, and Webpack, bringing a responsive 3D chess experience to the browser without blocking the main thread.', keywords: ['chess3d','chess','blender','web','worker','game','ai','typescript','three','three.js','webpack','3d','browser'] },
  { id: 'project-nyumbasmart', section: 'projects', title: 'NyumbaSmart', content: 'NyumbaSmart is an AI-powered apartment and facility management platform for African real estate operations. It includes tenant portals, rent payments, maintenance automation, analytics, and AI insights. Its listed technologies are AI, M-Pesa, and property operations.', keywords: ['nyumbasmart','apartment','facility','management','real','estate','tenant','rent','payments','maintenance','analytics','m-pesa','property'] },
  { id: 'project-beckwam', section: 'projects', title: 'Beckwam stores', content: 'Beckwam stores is a point-of-sale and inventory management system for store operations. It uses PHP, POS, and inventory management to keep sales and stock workflows organized in one practical retail system.', keywords: ['beckwam','stores','store','point','sale','pos','inventory','php','retail','sales','stock'] },
  { id: 'project-car-rental', section: 'projects', title: 'car-rental-project', content: 'car-rental-project is a PHP and MySQL car-rental application with an admin dashboard and separate customer and administrator interfaces. Customers can reserve vehicles while admins manage reservations and fleet operations.', keywords: ['car','rental','project','php','mysql','admin','dashboard','customer','administrator','reserve','vehicles','fleet'] },
  { id: 'project-saas', section: 'projects', title: 'saas-landing-page-design', content: 'saas-landing-page-design is a v0-built SaaS landing page in a modern Next.js App Router project. It uses Next.js 16, React 19, and Tailwind CSS, providing a polished, deployable marketing surface for a SaaS product.', keywords: ['saas','landing','page','design','v0','next','next.js','app','router','react','tailwind','marketing'] },
  { id: 'project-telemetry', section: 'projects', title: 'Telemetry Pipeline', content: 'Telemetry Pipeline is an event-driven Java, Apache Kafka, and PostgreSQL telemetry pipeline for multi-region observability. It makes service health visible before incidents reach customers.', keywords: ['telemetry','pipeline','event','java','apache','kafka','postgresql','observability','multi-region','service','health'] },
  { id: 'project-payflow', section: 'projects', title: 'PayFlow APIs', content: 'PayFlow APIs is a Spring Boot, REST, and MySQL payment integration layer. It simplifies secure payment orchestration for fintech platforms.', keywords: ['payflow','apis','spring','boot','rest','mysql','payment','integration','fintech'] },
  { id: 'project-nlp', section: 'projects', title: 'NLP Signals', content: 'NLP Signals is a Python, NLP, and neural networks text classification workflow for extracting business intent. It converts unstructured language into actionable product signals.', keywords: ['nlp','signals','python','neural','networks','text','classification','business','intent','language'] },
  { id: 'experience-gipperpay', section: 'experience', title: 'GipperPay Finance', content: 'From May 2023 to Present, Joseph has been Software Engineer Team Lead at GipperPay Finance. He owns architecture for multi-region microservices, built an Apache Kafka telemetry pipeline, and developed a RAG-based credit-profiling service that reduced client onboarding from 3 days to half a day.', keywords: ['gipperpay','finance','team','lead','may','2023','present','microservices','kafka','rag','credit','onboarding'] },
  { id: 'experience-deutsche', section: 'experience', title: 'Deutsche Schule Nairobi', content: 'From November 2024 to Present, Joseph has been an AI and Robotics Tutor at Deutsche Schule Nairobi, delivering technical training on algorithm design, robotics, and introductory AI through hands-on learning.', keywords: ['deutsche','schule','nairobi','ai','robotics','tutor','november','2024','algorithm','design'] },
  { id: 'experience-pesapal', section: 'experience', title: 'Pesapal Limited', content: 'From June 2022 to March 2023, Joseph was a Software Engineer at Pesapal Limited, building REST API payment integrations and optimizing database telemetry across PostgreSQL and MySQL.', keywords: ['pesapal','software','engineer','june','2022','march','2023','rest','api','payment','postgresql','mysql'] },
  { id: 'experience-cuea', section: 'experience', title: 'Catholic University of East Africa', content: 'From January 2020 to May 2020, Joseph was a Network Associate at Catholic University of East Africa, monitoring network device performance, maintaining uptime, and resolving connectivity incidents supporting remote learning infrastructure.', keywords: ['catholic','university','east','africa','network','associate','january','2020','may','connectivity','remote','learning'] },
  { id: 'experience-governance', section: 'experience', title: 'Governance and compliance', content: 'Joseph has governance and compliance experience backed by a Strathmore certification. The portfolio lists three projects in this domain: Data Mapping & Anonymization; Automated Regulatory Reporting dashboard; and open source startup compliance guide.', keywords: ['governance','compliance','strathmore','certification','data','mapping','anonymization','automated','regulatory','reporting','dashboard','open','source','startup','guide'] },
  { id: 'credentials', section: 'credentials', title: 'Credentials', content: 'Joseph has a BSc in Information Technology from JKUAT, with a Departmental Merit Prize for excellence in Predictive Data Infrastructure Modeling. Core credentials listed are CISA, CCNA, and a GRC Credential with Distinction. AI and cloud badges include PrivacyOps and AI Security from Securiti AI, plus Deep Learning and NLP.', keywords: ['bsc','information','technology','jkuat','merit','predictive','data','cisa','ccna','grc','distinction','privacyops','security','securiti','deep','learning'] },
  { id: 'contact', section: 'contact', title: 'Contact', content: 'Contact shown on the portfolio: Nairobi, Kenya; email joe.macibi@gmail.com; GitHub github.com/JoeMacibi; LinkedIn linkedin.com/in/joseph-macibi-3697b9198/.', keywords: ['contact','nairobi','kenya','email','joe.macibi@gmail.com','github','linkedin'] },
]

const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
const queryStopWords = new Set(['about', 'answer', 'are', 'can', 'does', 'how', 'is', 'joe', 'joseph', 'me', 'of', 'on', 'tell', 'the', 'what', 'which', 'who', 'with'])
const queryAliases: Record<string, string[]> = {
  mini: ['mini-wakili', 'mini_wakili.py'],
  wakili: ['mini-wakili', 'mini_wakili.py'],
  kiota: ['kiotapay', 'kiota pay'],
  pay: ['kiotapay', 'payment'],
  rag: ['retrieval augmented generation', 'grounded'],
}

export function retrievePortfolioChunks(question: string) {
  const normalizedQuestion = normalize(question)
  const terms = normalizedQuestion.split(' ').filter((term) => term.length > 2 && !queryStopWords.has(term))
  return portfolioChunks.map((chunk) => {
    const haystack = normalize(`${chunk.title} ${chunk.content} ${chunk.keywords.join(' ')}`)
    const exactPhrase = normalizedQuestion && haystack.includes(normalizedQuestion) ? 8 : 0
    const score = terms.reduce((total, term) => {
      const aliases = queryAliases[term] ?? []
      return total + (haystack.includes(term) ? 1 : 0) + aliases.reduce((aliasScore, alias) => aliasScore + (haystack.includes(normalize(alias)) ? 1 : 0), 0)
    }, exactPhrase)
    return { chunk, score }
  }).filter(({ score }) => score > 0).sort((a, b) => b.score - a.score).slice(0, 6).map(({ chunk }) => chunk)
}

export const portfolioFallback = "I don't see that information on Joe's portfolio."
export const portfolioSourceText = portfolioChunks.map((chunk) => `${chunk.title}\n${chunk.content}`).join('\n\n')
